### ISSUE TITLE
Define a constant for you rmax number to be generated

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/High-LowNumberGuessing#5]
https://github.com/thirdiblind/High-LowNumberGuessing/blob/bf731e58dbbc88267f97155aecb85ea1e5797d81/High-LowNumberGuessing/Program.cs#L11

Define a constant for 100. And take care, if you want to generate a number between 0 and 100, you need to know, that the random.Next(min,max) does not include the upper bound. So in fact, to make it work, you would need to do use 100+1.

![image](https://github.com/thirdiblind/High-LowNumberGuessing/assets/130921606/a318b451-087e-4946-a214-3d1af27717d4)

**Comment by incredibleLeitman** [comment]
Hey @thirdiblind this issue is not fixed ☝️ (as well as #1 )

You *have* fixed the part about the maximum random number, but still not using a defined constant in your code.

Currently in your code I see "101" in the code when generating the random number, but also a plain "100" in the console output to the user -> as a naive beginner developer I may not get that those magic numbers are connected to each other and change the rng.Next call to "Next(1, 11)" to have a smaller number generation, just to notice that the program still displays "Guess a number from 0-100."

Also, make sure that you create a constant for each configuration value, not if the actual numbers are the same per accident! ☝️ 
Imagine you want to change the amount of guesses the user has, and suddently this also affects the range for a close guess,
this is very confusing.

And finally, ```GUESSES_INITIAL_AMOUNT ``` is not a very good name. Its obvious that this is the "initial" value because its directly set to this constant, and "guesses" and "amount" are kinda redundant. Better names would be for example "MAX_GUESSES" or "GUESS_COUNT"
